__Map__


- một hàm lấy một tập giá trị và "ánh xạ" chúng thành một tập giá trị khác.

- Trong khoa học dữ liệu, tạo ra các biểu diễn mới từ dữ liệu hiện có, hoặc chuyển đổi dữ liệu từ định dạng hiện tại sang định dạng mong muốn sau này

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../titanic3.csv')
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [6]:
df_age_mean = df.age.mean() # Lấy số trung bình của tuổi
print(df_age_mean)

29.881137667304014

In [7]:
df.age.map(lambda age: age - df_age_mean)

0       -0.881138
1      -28.961138
2      -27.881138
3        0.118862
4       -4.881138
          ...
1304   -15.381138
1305          NaN
1306    -3.381138
1307    -2.881138
1308    -0.881138
Name: age, Length: 1309, dtype: float64

In [10]:
def remean_age(row):
    row.age = row.age - df_age_mean
    return row

df.apply(remean_age, axis='columns') # Axis có 2 giá trị: 0 (hoặc 'index') và 1 (hoặc 'columns')

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,-0.881138,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,-28.961138,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,-27.881138,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,0.118862,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,-4.881138,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,-15.381138,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,-3.381138,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,-2.881138,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,-0.881138,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN