In [1]:
import pandas as pd

Validate: Các loại merge, join, concat trong pandas
- One-to-One: Mỗi giá trị trong cột khóa của DataFrame này khớp với đúng một giá trị trong cột khóa của DataFrame kia.
- Many-to-One: Nhiều giá trị trong cột khóa của DataFrame này khớp với một giá trị duy nhất trong cột khóa của DataFrame kia.
- Many-to-Many: Nhiều giá trị trong cột khóa của DataFrame này khớp với nhiều giá trị trong cột khóa của DataFrame kia.

In [6]:
# concat() = Với một danh sách các phần tử, hàm này sẽ gộp các phần tử đó lại với nhau dọc theo một trục.
# TODO: chỉ dùng được cho dữ liệu khác nhau nhưng có cùng trường (cột)
# Độ phức tạp: dễ
jp_videos = pd.read_csv('./JPvideos.csv', encoding='utf-8', encoding_errors='replace') # vì jp có nhiều kí tự đặc biệt nên cần encoding
us_videos = pd.read_csv('./USvideos.csv')

pd.concat([jp_videos, us_videos], axis=0, ignore_index=False, keys=['JP', 'US'])

             video_id trending_date  \
JP 0      5ugKfHgsmYw      18.07.02
   1      ohObafdd34Y      18.07.02
   2      aBr2kKAHN6M      18.07.02
   3      5wNnwChvmsQ      18.07.02
   4      B7J47qFvdsk      18.07.02
...               ...           ...
US 40944  BZt0qjTWNhw      18.14.06
   40945  1h7KV2sjUWY      18.14.06
   40946  D6Oy4LfoqsU      18.14.06
   40947  oV0zkMe1K8s      18.14.06
   40948  ooyjaVdt-jA      18.14.06

                                                      title  \
JP 0                                     陸自ヘリ、垂直に落下＝路上の車が撮影
   1                                 イッテQ お祭り男宮川×手越 巨大ブランコ②
   2                                  Live Views of Starman
   3                             東京ディズニーリゾートの元キャストが暴露した秘密5選
   4              榮倉奈々、衝撃の死んだふり！映画『家に帰ると妻が必ず死んだふりをしています。』特報
...                                                     ...
US 40944                       The Cat Who Caught the Laser
   40945                         True Facts : Ant Mutualism
   40946  I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...
   40947                How Black Panther Should Have Ended
   40948  Official Call of Duty®: Black Ops 4 — Multipla...

                     channel_title  category_id              publish_time  \
JP 0                    時事通信映像センター           25  2018-02-06T03:04:37.000Z
   1          神谷えりな Kamiya Erina 2            1  2018-02-06T04:01:56.000Z
   2                        SpaceX           28  2018-02-06T21:38:22.000Z
   3                       アシタノワダイ           25  2018-02-06T06:08:49.000Z
   4                       シネマトゥデイ            1  2018-02-06T02:30:00.000Z
...                            ...          ...                       ...
US 40944             AaronsAnimals           15  2018-05-18T13:00:04.000Z
   40945                  zefrank1           22  2018-05-18T01:00:06.000Z
   40946                Brad Mondo           24  2018-05-18T17:34:22.000Z
   40947  How It Should Have Ended            1  2018-05-17T17:00:04.000Z
   40948              Call of Duty           20  2018-05-17T17:09:38.000Z

                                                       tags     views   likes  \
JP 0      事故|"佐賀"|"佐賀県"|"ヘリコプター"|"ヘリ"|"自衛隊"|"墜落"|"落下"|"現...    188085     591
   1                                                 [none]     90929     442
   2                                                 [none]   6408303  165892
   3                                                アシタノワダイ     96255    1165
   4                                                 [none]    108408    1336
...                                                     ...       ...     ...
US 40944  aarons animals|"aarons"|"animals"|"cat"|"cats"...   1685609   38160
   40945                                             [none]   1064798   60008
   40946  I gave safiya nygaard a perfect hair makeover ...   1066451   48068
   40947  Black Panther|"HISHE"|"Marvel"|"Infinity War"|...   5660813  192957
   40948      call of duty|"cod"|"activision"|"Black Ops 4"  10306119  357079

          dislikes  comment_count  \
JP 0           189              0
   1            88            174
   2          2331           3006
   3           277            545
   4            74            201
...            ...            ...
US 40944      1385           2657
   40945       382           3936
   40946      1032           3992
   40947      2846          13088
   40948    212976         144795

                                          thumbnail_link  comments_disabled  \
JP 0      https://i.ytimg.com/vi/5ugKfHgsmYw/default.jpg               True
   1      https://i.ytimg.com/vi/ohObafdd34Y/default.jpg              False
   2      https://i.ytimg.com/vi/aBr2kKAHN6M/default.jpg              False
   3      https://i.ytimg.com/vi/5wNnwChvmsQ/default.jpg              False
   4      https://i.ytimg.com/vi/B7J47qFvdsk/default.jpg              False
...                                                  ...                ...
US 40944  https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg              False
   40945  https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg              False
   40946  https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg              False
   40947  https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg              False
   40948  https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg              False

          ratings_disabled  video_error_or_removed  \
JP 0                 False                   False
   1                 False                   False
   2                 False                   False
   3                 False                   False
   4                 False                   False
...                    ...                     ...
US 40944             False                   False
   40945             False                   False
   40946             False                   False
   40947             False                   False
   40948             False                   False

                                                description
JP 0      佐賀県神埼市の民家に墜落した陸上自衛隊のＡＨ６４Ｄ戦闘ヘリコプターが垂直に落下する様子を、近...
   1                                                    NaN
   2                                                    NaN
   3      東京ディズニーリゾートの元キャストが暴露した秘密5選\n\nかたまりクリエイトさま\n【検証...
   4      家に帰ってきたサラリーマンのじゅん（安田顕）は、玄関で血を出して倒れている妻ちえ（榮倉奈々）...
...                                                     ...
US 40944     The Cat Who Caught the Laser - Aaron's Animals
   40945                                                NaN
   40946  I had so much fun transforming Safiyas hair in...
   40947  How Black Panther Should Have EndedWatch More ...
   40948  Call of Duty: Black Ops 4 Multiplayer raises t...

[61472 rows x 16 columns]

In [ ]:
# join() : kết hợp các đối tượng DataFrame khác nhau có chung một chỉ mục.
# Độ phức tạp: vừa 
left = jp_videos.set_index(['title', 'trending_date'])
right = us_videos.set_index(['title', 'trending_date']) # set_index(): đặt chỉ mục

left.join(right, lsuffix='_JP', rsuffix='_US', how='outer') # lsuffix, rsuffix: hậu tố thêm vào tên cột để phân biệt
# how='outer': giữ tất cả các hàng từ cả hai DataFrame, nếu không có giá trị tương ứng thì sẽ là NaN

                                                                  video_id_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06       UI8ULXKJamA
#00 雉尾つぐ                                           18.14.05       5-3bbwUzIoY
                                                   18.14.05       5-3bbwUzIoY
                                                   18.15.05       5-3bbwUzIoY
                                                   18.15.05       5-3bbwUzIoY
...                                                                       ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04       oTlz6MWvY-c
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05       V0C01FsfDiw
😱 $1,145 iPhone Case!!                             18.04.02               NaN
                                                   18.05.02               NaN
                                                   18.06.02               NaN

                                                                 channel_title_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06               !t Live
#00 雉尾つぐ                                           18.14.05                  鳩羽つぐ
                                                   18.14.05                  鳩羽つぐ
                                                   18.15.05                  鳩羽つぐ
                                                   18.15.05                  鳩羽つぐ
...                                                                           ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04                スカッとGJ
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05         日本の政治 CHANNEL
😱 $1,145 iPhone Case!!                             18.04.02                   NaN
                                                   18.05.02                   NaN
                                                   18.06.02                   NaN

                                                                  category_id_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06                 24.0
#00 雉尾つぐ                                           18.14.05                  1.0
                                                   18.14.05                  1.0
                                                   18.15.05                  1.0
                                                   18.15.05                  1.0
...                                                                          ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04                 24.0
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05                 25.0
😱 $1,145 iPhone Case!!                             18.04.02                  NaN
                                                   18.05.02                  NaN
                                                   18.06.02                  NaN

                                                                           publish_time_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06       2018-06-11T11:43:26.000Z
#00 雉尾つぐ                                           18.14.05       2018-05-13T12:10:10.000Z
                                                   18.14.05       2018-05-13T12:10:10.000Z
                                                   18.15.05       2018-05-13T12:10:10.000Z
                                                   18.15.05       2018-05-13T12:10:10.000Z
...                                                                                    ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04       2018-04-26T05:04:03.000Z
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05       2018-05-10T01:30:22.000Z
😱 $1,145 iPhone Case!!                             18.04.02                            NaN
                                                   18.05.02                            NaN
                                                   18.06.02                            NaN

                                                                                                            tags_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06       샤이니|"SHINee"|"태민"|"민호"|"온유"|"키"|"종현"|"TAEMIN"|...
#00 雉尾つぐ                                           18.14.05       バーチャルyoutuber|"vtuber"|"バーチャルユーチューバー"|"鳩羽つぐ"|"...
                                                   18.14.05       バーチャルyoutuber|"vtuber"|"バーチャルユーチューバー"|"鳩羽つぐ"|"...
                                                   18.15.05       バーチャルyoutuber|"vtuber"|"バーチャルユーチューバー"|"鳩羽つぐ"|"...
                                                   18.15.05       バーチャルyoutuber|"vtuber"|"バーチャルユーチューバー"|"鳩羽つぐ"|"...
...                                                                                                             ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04       TOKIO|"山口達也"|"強制わいせつ"|"書類送検"|"加藤浩次"|"スッキリ"|"極楽...
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05                               長妻昭|"立憲民主党"|"柳瀬唯夫"|"加計学園"
😱 $1,145 iPhone Case!!                             18.04.02                                                     NaN
                                                   18.05.02                                                     NaN
                                                   18.06.02                                                     NaN

                                                                  views_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06        45348.0
#00 雉尾つぐ                                           18.14.05       260277.0
                                                   18.14.05       260277.0
                                                   18.15.05       445201.0
                                                   18.15.05       445201.0
...                                                                    ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04        68455.0
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05        13846.0
😱 $1,145 iPhone Case!!                             18.04.02            NaN
                                                   18.05.02            NaN
                                                   18.06.02            NaN

                                                                  likes_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06         4124.0
#00 雉尾つぐ                                           18.14.05        11517.0
                                                   18.14.05        11517.0
                                                   18.15.05        14287.0
                                                   18.15.05        14287.0
...                                                                    ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04           19.0
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05           64.0
😱 $1,145 iPhone Case!!                             18.04.02            NaN
                                                   18.05.02            NaN
                                                   18.06.02            NaN

                                                                  dislikes_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06              29.0
#00 雉尾つぐ                                           18.14.05             178.0
                                                   18.14.05             178.0
                                                   18.15.05             316.0
                                                   18.15.05             316.0
...                                                                       ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04             135.0
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05              24.0
😱 $1,145 iPhone Case!!                             18.04.02               NaN
                                                   18.05.02               NaN
                                                   18.06.02               NaN

                                                                  comment_count_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06                  146.0
#00 雉尾つぐ                                           18.14.05                 2855.0
                                                   18.14.05                 2855.0
                                                   18.15.05                 3403.0
                                                   18.15.05                 3403.0
...                                                                            ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04                   15.0
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05                   47.0
😱 $1,145 iPhone Case!!                             18.04.02                    NaN
                                                   18.05.02                    NaN
                                                   18.06.02                    NaN

                                                                                               thumbnail_link_JP  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06       https://i.ytimg.com/vi/UI8ULXKJamA/default.jpg
#00 雉尾つぐ                                           18.14.05       https://i.ytimg.com/vi/5-3bbwUzIoY/default.jpg
                                                   18.14.05       https://i.ytimg.com/vi/5-3bbwUzIoY/default.jpg
                                                   18.15.05       https://i.ytimg.com/vi/5-3bbwUzIoY/default.jpg
                                                   18.15.05       https://i.ytimg.com/vi/5-3bbwUzIoY/default.jpg
...                                                                                                          ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04       https://i.ytimg.com/vi/oTlz6MWvY-c/default.jpg
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05       https://i.ytimg.com/vi/V0C01FsfDiw/default.jpg
😱 $1,145 iPhone Case!!                             18.04.02                                                  NaN
                                                   18.05.02                                                  NaN
                                                   18.06.02                                                  NaN

                                                                  ...  \
title                                              trending_date  ...
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06       ...
#00 雉尾つぐ                                           18.14.05       ...
                                                   18.14.05       ...
                                                   18.15.05       ...
                                                   18.15.05       ...
...                                                               ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04       ...
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05       ...
😱 $1,145 iPhone Case!!                             18.04.02       ...
                                                   18.05.02       ...
                                                   18.06.02       ...

                                                                                                            tags_US  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06                                                     NaN
#00 雉尾つぐ                                           18.14.05                                                     NaN
                                                   18.14.05                                                     NaN
                                                   18.15.05                                                     NaN
                                                   18.15.05                                                     NaN
...                                                                                                             ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04                                                     NaN
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05                                                     NaN
😱 $1,145 iPhone Case!!                             18.04.02       ijustine|"gray international"|"most expensive ...
                                                   18.05.02       ijustine|"gray international"|"most expensive ...
                                                   18.06.02       ijustine|"gray international"|"most expensive ...

                                                                  views_US  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06            NaN
#00 雉尾つぐ                                           18.14.05            NaN
                                                   18.14.05            NaN
                                                   18.15.05            NaN
                                                   18.15.05            NaN
...                                                                    ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04            NaN
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05            NaN
😱 $1,145 iPhone Case!!                             18.04.02       408713.0
                                                   18.05.02       673040.0
                                                   18.06.02       734863.0

                                                                 likes_US  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06           NaN
#00 雉尾つぐ                                           18.14.05           NaN
                                                   18.14.05           NaN
                                                   18.15.05           NaN
                                                   18.15.05           NaN
...                                                                   ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04           NaN
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05           NaN
😱 $1,145 iPhone Case!!                             18.04.02       15040.0
                                                   18.05.02       18904.0
                                                   18.06.02       19965.0

                                                                 dislikes_US  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06              NaN
#00 雉尾つぐ                                           18.14.05              NaN
                                                   18.14.05              NaN
                                                   18.15.05              NaN
                                                   18.15.05              NaN
...                                                                      ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04              NaN
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05              NaN
😱 $1,145 iPhone Case!!                             18.04.02           2038.0
                                                   18.05.02           3852.0
                                                   18.06.02           4110.0

                                                                 comment_count_US  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06                   NaN
#00 雉尾つぐ                                           18.14.05                   NaN
                                                   18.14.05                   NaN
                                                   18.15.05                   NaN
                                                   18.15.05                   NaN
...                                                                           ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04                   NaN
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05                   NaN
😱 $1,145 iPhone Case!!                             18.04.02                2617.0
                                                   18.05.02                3639.0
                                                   18.06.02                3553.0

                                                                                               thumbnail_link_US  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06                                                  NaN
#00 雉尾つぐ                                           18.14.05                                                  NaN
                                                   18.14.05                                                  NaN
                                                   18.15.05                                                  NaN
                                                   18.15.05                                                  NaN
...                                                                                                          ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04                                                  NaN
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05                                                  NaN
😱 $1,145 iPhone Case!!                             18.04.02       https://i.ytimg.com/vi/r3J784MSRyQ/default.jpg
                                                   18.05.02       https://i.ytimg.com/vi/r3J784MSRyQ/default.jpg
                                                   18.06.02       https://i.ytimg.com/vi/r3J784MSRyQ/default.jpg

                                                                  comments_disabled_US  \
title                                              trending_date
!t Live Special : The 7th MUGI-BOX SHINee          18.12.06                        NaN
#00 雉尾つぐ                                           18.14.05                        NaN
                                                   18.14.05                        NaN
                                                   18.15.05                        NaN
                                                   18.15.05                        NaN
...                                                                                ...
🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】   18.27.04                        NaN
😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員会... 18.11.05                        NaN
😱 $1,145 iPhone Case!!                             18.04.02                      False
                                                   18.05.02                      False

In [14]:
# merge() : kết hợp các đối tượng DataFrame khác nhau dựa trên các cột chung
# Độ phức tạp: vừa
# Ví dụ: kết hợp hai DataFrame dựa trên cột 'title' và 'trending_date'
merged_videos = pd.merge(left=jp_videos, right=us_videos, 
                         on=['title', 'trending_date'], # cột chung để merge
                         suffixes=('_JP', '_US'),
                         how='outer')
merged_videos

,video_id_JP,trending_date,title,channel_title_JP,category_id_JP,publish_time_JP,tags_JP,views_JP,likes_JP,dislikes_JP,...,tags_US,views_US,likes_US,dislikes_US,comment_count_US,thumbnail_link_US,comments_disabled_US,ratings_disabled_US,video_error_or_removed_US,description_US
0,UI8ULXKJamA,18.12.06,!t Live Special : The 7th MUGI-BOX SHINee,!t Live,24.0,2018-06-11T11:43:26.000Z,"샤이니|""SHINee""|""태민""|""민호""|""온유""|""키""|""종현""|""TAEMIN""|...",45348.0,4124.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5-3bbwUzIoY,18.14.05,#00 雉尾つぐ,鳩羽つぐ,1.0,2018-05-13T12:10:10.000Z,"バーチャルyoutuber|""vtuber""|""バーチャルユーチューバー""|""鳩羽つぐ""|""...",260277.0,11517.0,178.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5-3bbwUzIoY,18.14.05,#00 雉尾つぐ,鳩羽つぐ,1.0,2018-05-13T12:10:10.000Z,"バーチャルyoutuber|""vtuber""|""バーチャルユーチューバー""|""鳩羽つぐ""|""...",260277.0,11517.0,178.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5-3bbwUzIoY,18.15.05,#00 雉尾つぐ,鳩羽つぐ,1.0,2018-05-13T12:10:10.000Z,"バーチャルyoutuber|""vtuber""|""バーチャルユーチューバー""|""鳩羽つぐ""|""...",445201.0,14287.0,316.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5-3bbwUzIoY,18.15.05,#00 雉尾つぐ,鳩羽つぐ,1.0,2018-05-13T12:10:10.000Z,"バーチャルyoutuber|""vtuber""|""バーチャルユーチューバー""|""鳩羽つぐ""|""...",445201.0,14287.0,316.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61344,oTlz6MWvY-c,18.27.04,🔴加藤浩次、TOKIO山口達也の行動へ怒り｢どんだけメンバーに迷惑かけてんの｣ 【スカッとＧＪ】,スカッとGJ,24.0,2018-04-26T05:04:03.000Z,"TOKIO|""山口達也""|""強制わいせつ""|""書類送検""|""加藤浩次""|""スッキリ""|""極楽...",68455.0,19.0,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61345,V0C01FsfDiw,18.11.05,😮長妻昭・立憲民主党《加計学園問題、柳瀬唯夫元首相秘書官参考人》【国会中継 衆議院 予算委員...,日本の政治 CHANNEL,25.0,2018-05-10T01:30:22.000Z,"長妻昭|""立憲民主党""|""柳瀬唯夫""|""加計学園""",13846.0,64.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61346,NaN,18.04.02,"😱 $1,145 iPhone Case!!",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"ijustine|""gray international""|""most expensive ...",408713.0,15040.0,2038.0,2617.0,https://i.ytimg.com/vi/r3J784MSRyQ/default.jpg,False,False,False,What do you guys thing of this iPhone Case?!\n...
61347,NaN,18.05.02,"😱 $1,145 iPhone Case!!",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"ijustine|""gray international""|""most expensive ...",673040.0,18904.0,3852.0,3639.0,https://i.ytimg.com/vi/r3J784MSRyQ/default.jpg,False,False,False,What do you guys thing of this iPhone Case?!\n...
61348,NaN,18.06.02,"😱 $1,145 iPhone Case!!",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"ijustine|""gray international""|""most expensive ...",734863.0,19965.0,4110.0,3553.0,https://i.ytimg.com/vi/r3J784MSRyQ/default.jpg,False,False,False,What do you guys thing of this iPhone Case?!\n...

# Merge_ordered

Dùng khi:
- Ordered data/ time series
- Fill missing values

In [7]:
aapl = pd.DataFrame({
    "date": ["2007-02-01", "2007-03-01", "2007-04-01", "2007-05-01", "2007-06-01"],
    "close": [12.087143, 13.272857, 14.257143, 17.312857, 17.434286]
})

mcd = pd.DataFrame({
    "date": ["2007-01-01", "2007-02-01", "2007-03-01", "2007-04-01", "2007-05-01"],
    "close": [44.349998, 43.689999, 45.049999, 48.279999, 50.549999]
})

In [10]:
pd.merge_ordered(aapl, mcd, on="date", suffixes=('_aapl' ,'_mcd'), fill_method='ffill') # ffile (Forward fill)

         date  close_aapl  close_mcd
0  2007-01-01         NaN  44.349998
1  2007-02-01   12.087143  43.689999
2  2007-03-01   13.272857  45.049999
3  2007-04-01   14.257143  48.279999
4  2007-05-01   17.312857  50.549999
5  2007-06-01   17.434286  50.549999