# Inner join

Giữ chỉ các dòng có khóa trùng nhau ở cả 2 bảng

In [13]:
import pandas as pd

In [14]:
table_1 = pd.DataFrame({
    "A" : ["A2", "A3", "A4"],
    "B" : ["B2", "B3", "B4"],
    "C" : ["C2", "C3", "C4"],
})

table_2 = pd.DataFrame({
    "C" : ["C1", "C2", "C4", "C5"],
    "D" : ["D1" ,"D2", "D4", "D5"],
})

In [15]:
table_1

    A   B   C
0  A2  B2  C2
1  A3  B3  C3
2  A4  B4  C4

In [16]:
table_2

    C   D
0  C1  D1
1  C2  D2
2  C4  D4
3  C5  D5

In [17]:
table_1 = table_1.merge(table_2, on="C", how="inner")

In [18]:
table_1

    A   B   C   D
0  A2  B2  C2  D2
1  A4  B4  C4  D4

# Left join

Giữ toàn bộ dòng bên trái, thêm dữ liệu từ bảng phải nếu có

In [20]:
table_1 = pd.DataFrame({
    "A" : ["A2", "A3", "A4"],
    "B" : ["B2", "B3", "B4"],
    "C" : ["C2", "C3", "C4"],
})

table_2 = pd.DataFrame({
    "C" : ["C1", "C2", "C4", "C5"],
    "D" : ["D1" ,"D2", "D4", "D5"],
})

print(table_1)

    A   B   C
0  A2  B2  C2
1  A3  B3  C3
2  A4  B4  C4

In [21]:
table_1 = table_1.merge(table_2, on="C", how="left")

In [22]:
table_1

    A   B   C    D
0  A2  B2  C2   D2
1  A3  B3  C3  NaN
2  A4  B4  C4   D4

# Right join

Giữ toàn bộ dòng bên phải

In [25]:
left_table = pd.DataFrame({
    "A" : ["A2", "A3", "A4"],
    "B" : ["B2", "B3", "B4"],
    "C" : ["C2", "C3", "C4"],
})

right_table = pd.DataFrame({
    "C" : ["C1", "C2", "C4", "C5"],
    "D" : ["D1" ,"D2", "D4", "D5"],
})

print(left_table)
print(right_table)

    A   B   C
0  A2  B2  C2
1  A3  B3  C3
2  A4  B4  C4
    C   D
0  C1  D1
1  C2  D2
2  C4  D4
3  C5  D5

In [26]:
left_table = left_table.merge(right_table, on="C", how="right")

In [28]:
left_table

     A    B   C   D
0  NaN  NaN  C1  D1
1   A2   B2  C2  D2
2   A4   B4  C4  D4
3  NaN  NaN  C5  D5

# Outer join

Giữ tất cả dòng, kể cả không trùng khóa (NaN nếu thiếu)

In [29]:
left_table = pd.DataFrame({
    "A" : ["A2", "A3", "A4"],
    "B" : ["B2", "B3", "B4"],
    "C" : ["C2", "C3", "C4"],
})

right_table = pd.DataFrame({
    "C" : ["C1", "C2", "C4", "C5"],
    "D" : ["D1" ,"D2", "D4", "D5"],
})

print(left_table)
print(right_table)

    A   B   C
0  A2  B2  C2
1  A3  B3  C3
2  A4  B4  C4
    C   D
0  C1  D1
1  C2  D2
2  C4  D4
3  C5  D5

In [30]:
left_table = left_table.merge(right_table, on="C", how="outer")

In [31]:
left_table

     A    B   C    D
0  NaN  NaN  C1   D1
1   A2   B2  C2   D2
2   A3   B3  C3  NaN
3   A4   B4  C4   D4
4  NaN  NaN  C5   D5

# Self join

In [33]:
sequels = pd.DataFrame({
    "id" : [19995, 862, 863, 597, 24428],
    "title" : ["Avatar", "Toy Story", "Toy Story 2", "Titanic", "The Ave"],
    "sequel" : [None, 863, 10193, None, None],
})

In [34]:
original_sequels = sequels.merge(sequels, left_on="sequel", right_on="id", suffixes=("_original", "sequel"))

In [ ]:
original_sequels

,id_original,title_original,sequel_original,idsequel,titlesequel,sequelsequel
0,862,Toy Story,863.0,863,Toy Story 2,10193.0