**Data Frame** = là một CTDL trong python, lưu trữ dữ liệu dưới dạng bảng (khá giống Excel)

In [6]:
import pandas as pd
import numpy as np

## 1.Create datafram from an array

### 1.1 Option 1

In [7]:
# Creating an array
data = np.array([[1,4], [2,5], [3,6]])

In [8]:
# Creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])

In [9]:
# Showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

### 1.2 Option 2

In [10]:
# Creating an array with list shape
data = [[1,4], [2,5], [3,6]]

In [11]:
# Creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])

In [12]:
# Showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

### 1.3 Option 3

In [13]:
pd.DataFrame(data={'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

## 2. Create a Dataframe from dictionary

In [14]:
# list used for this example
states = ['California', 'Texas', 'Florida', 'New York']
population = [39538223, 29145505, 21538187, 20201249]

In [15]:
# Storing list within a dictionary
dict_states = {'States' : states, 'Population': population}

In [16]:
# Creating the dataframe
df_population = pd.DataFrame(dict_states)

In [17]:
# Showing the dataframe
df_population

       States  Population
0  California    39538223
1       Texas    29145505
2     Florida    21538187
3    New York    20201249

## 3. Create a DataFrame from a csv file

In [18]:
# reading the csv file
df_people = pd.read_csv("../titanic3.csv")

In [19]:
# Show first 5 rows of the dataframe
df_people.head() # head(n) : n is the number of the rows

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

## 4. Save a DataFrame as a csv file

In [21]:
df_population.to_csv('population.csv', index= False) # index = False: do not save the index column